title: "DIY with Andrew"
author: "Andrew Fang"
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I'm Andrew Fang, and I write about all kinds of DIY projects based on needs I have encountered in my personal life. This blog serves as an archive of the various tips and tricks I have come across from my extensive Googling.
permalink: /:title/
lang: "en"
excerpt_separator: "<!--more-->"
date_format: "%B %d, %Y"
email: blog@andrewbfang.com

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://andrewbfang.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: G-X4HVC6LRMX

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: Home, url: "https://andrewbfang.com"}
  - {title: Blog, url: "index.html"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Home, icon: globe, url: "https://andrewbfang.com"}
  - {title: Mail, icon: envelope, url: "mailto:blog@andrewbfang.com"}
  - {title: Github, icon: github, url: "https://github.com/andrewfang"}
  - {title: LinkedIn, icon: linkedin, url: "https://linkedin.com/in/andrewbfang"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: "afang"    # see https://disqus.com/
  isso_domain: "isso.andrewbfang.com"         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
